"""Versão inicial do banco de dados com multi-tenancy

Revision ID: 24321f763f4b
Revises: 
Create Date: 2025-11-12 17:08:05.653113

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '24321f763f4b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('clients',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('plan', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('clientes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('cpf_cnpj', sa.String(length=20), nullable=False),
    sa.Column('rg', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('telefone', sa.String(length=20), nullable=True),
    sa.Column('telefone_secundario', sa.String(length=20), nullable=True),
    sa.Column('chave_pix', sa.String(length=255), nullable=False),
    sa.Column('endereco', sa.String(length=255), nullable=False),
    sa.Column('cidade', sa.String(length=100), nullable=False),
    sa.Column('estado', sa.String(length=2), nullable=False),
    sa.Column('cep', sa.String(length=10), nullable=False),
    sa.Column('referencia', sa.String(length=255), nullable=False),
    sa.Column('telefone_referencia', sa.String(length=20), nullable=False),
    sa.Column('endereco_referencia', sa.String(length=255), nullable=False),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('empresa', sa.String(length=100), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('cpf_cnpj', 'client_id', name='uq_customer_cpf_client')
    )
    op.create_table('configuracoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chave', sa.String(length=100), nullable=False),
    sa.Column('valor', sa.Text(), nullable=True),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('chave', 'client_id', name='uq_config_chave_client')
    )
    op.create_table('usuarios',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('nome', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('senha', sa.String(length=255), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('nivel', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email', 'client_id', name='uq_user_email_client')
    )
    op.create_table('cobrancas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('descricao', sa.Text(), nullable=True),
    sa.Column('valor_original', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('multa', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('juros', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('desconto', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('valor_total', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('taxa_juros', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('numero_parcelas', sa.Integer(), nullable=False),
    sa.Column('parcela_atual', sa.Integer(), nullable=False),
    sa.Column('tipo_cobranca', sa.String(length=50), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('documentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('nome_ficheiro', sa.String(length=255), nullable=False),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('historico_pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cobranca_id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.DateTime(), nullable=False),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['cobranca_id'], ['cobrancas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notificacoes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cliente_id', sa.Integer(), nullable=False),
    sa.Column('cobranca_id', sa.Integer(), nullable=False),
    sa.Column('tipo', sa.String(length=50), nullable=False),
    sa.Column('mensagem', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('data_envio', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cliente_id'], ['clientes.id'], ),
    sa.ForeignKeyConstraint(['cobranca_id'], ['cobrancas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('pagamentos',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cobranca_id', sa.Integer(), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=False),
    sa.Column('observacao', sa.Text(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('usuario_id', sa.Integer(), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cobranca_id'], ['cobrancas.id'], ),
    sa.ForeignKeyConstraint(['usuario_id'], ['usuarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('parcelas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('cobranca_id', sa.Integer(), nullable=False),
    sa.Column('numero_parcela', sa.Integer(), nullable=False),
    sa.Column('valor', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_vencimento', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('valor_pago', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('data_pagamento', sa.Date(), nullable=True),
    sa.Column('forma_pagamento', sa.String(length=50), nullable=True),
    sa.Column('observacoes', sa.Text(), nullable=True),
    sa.Column('multa_manual', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('criado_em', sa.DateTime(), nullable=False),
    sa.Column('atualizado_em', sa.DateTime(), nullable=False),
    sa.Column('client_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['client_id'], ['clients.id'], ),
    sa.ForeignKeyConstraint(['cobranca_id'], ['cobrancas.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('parcelas')
    op.drop_table('pagamentos')
    op.drop_table('notificacoes')
    op.drop_table('historico_pagamentos')
    op.drop_table('documentos')
    op.drop_table('cobrancas')
    op.drop_table('usuarios')
    op.drop_table('configuracoes')
    op.drop_table('clientes')
    op.drop_table('clients')
    # ### end Alembic commands ###
